#pragma once

#include "NativeGameplayTags.h"

namespace AlsViewModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace AlsLocomotionModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace AlsRotationModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
}

namespace AlsStanceTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
}

namespace AlsGaitTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace AlsOverlayModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
}

namespace AlsLocomotionActionTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp)
}

namespace AlsGroundedEntryModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FromRoll)
}

namespace AlsCurveTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Curves)

	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AllowAiming)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AllowTransitions)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FeetCrossing)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FootLeftIk)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FootLeftLock)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FootPlanted)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FootRightIk)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FootRightLock)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FootstepSoundBlock)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroundPredictionBlock)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandLeftIk)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandRightIk)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HipsDirectionLock)

	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmLeft)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmLeftAdditive)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmLeftLocalSpace)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmLeftSlot)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmRight)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmRightAdditive)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmRightLocalSpace)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerArmRightSlot)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerHandLeft)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerHandRight)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerHead)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerHeadAdditive)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerHeadSlot)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerLegs)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerLegsSlot)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerPelvis)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerPelvisSlot)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerSpine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerSpineAdditive)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerSpineSlot)

	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoseCrouching)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoseGait)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoseGrounded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoseInAir)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoseMoving)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PoseStanding)

	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RotationYawOffset)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RotationYawSpeed)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SprintBlock)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewBlock)
}
